[#13]fix Readme examples
radicalbit/flink-jpmml pull request #14
Opened 2017-06-15 11:13 UTC by francescofrontera

2017-06-15 18:33 UTC, spi-x-i requested changes

2017-06-15 18:33 UTC, spi-x-i commented on flink-jpmml-examples/README.md
> +./path/to/bin/flink run -c io.radicalbit.examples.EvaluateKmeans path/to/flink-jpmml/flink-jpmml-examples/target/scala-2.11/flink-jpmml-examples-assembly-0.6.0-SNAPSHOT.jar --model path/to/pmml/model
I think  `</path/to/project/root>/flink-jpmml-examples/target/scala-2.11/flink-jpmml-examples-assembly-0.6.0-SNAPSHOT.jar` is better in both cases. I believe also `scala-2.11` is correct only if users assembly the project with scala 2.11

2017-06-20 14:21 UTC, spi-x-i approved these changes

2017-06-20 15:37 UTC, maocorte approved these changes

2017-06-20 15:37 UTC, merged