Feature/26 extending evaluator adt with empty predictions
radicalbit/flink-jpmml pull request #34
Opened 2017-09-19 15:25 UTC by riccardo14

2017-09-19 15:55 UTC, spi-x-i requested changes

2017-09-19 15:55 UTC, spi-x-i commented on flink-jpmml-scala/src/main/scala/io/radicalbit/flink/pmml/scala/api/Evaluator.scala
> +  * Represent the Evaluator of a PmmlModel
Represents

2017-09-19 15:55 UTC, spi-x-i commented on flink-jpmml-scala/src/main/scala/io/radicalbit/flink/pmml/scala/api/PmmlModel.scala
> +    * @return
Please, provide return field description

2017-09-20 08:30 UTC, maocorte approved these changes

2017-09-20 09:34 UTC, spi-x-i approved these changes

2017-09-20 09:36 UTC, merged