[#28] Updated flink jpmml examples
radicalbit/flink-jpmml pull request #39
Opened 2017-09-20 12:50 UTC by francescofrontera

this PR refers to #28  issue.

2017-09-20 13:27 UTC, riccardo14 approved these changes

2017-09-20 15:29 UTC, spi-x-i requested changes
Please, align the PR correctly.

2017-09-20 15:51 UTC, spi-x-i requested changes
In general LGTM, IMHO I don't like so much plain examples without any comment. The user potentially struggles to understand what is going on there.

2017-09-20 15:51 UTC, spi-x-i commented on flink-jpmml-examples/README.md
> +Iris(,sepalLength: Double, sepalWidth: Double, petalLength: Double, petalWidth: Double)
Is the comma needed?

2017-09-20 15:51 UTC, spi-x-i commented on flink-jpmml-examples/README.md
> +## Fault-Tolerant
`##Fault-Tolerance`

2017-09-20 15:51 UTC, spi-x-i commented on flink-jpmml-examples/README.md
> +if you like testing a fault-tolerant of the operator you can run a `CheckpointEvaluate` example.
`If you like testing the fault-tolerance feature ..`

2017-09-20 15:51 UTC, spi-x-i commented on flink-jpmml-examples/README.md
> +
... And then?

2017-09-20 15:51 UTC, spi-x-i commented on flink-jpmml-examples/src/main/scala/io/radicalbit/examples/DynamicEvaluateKmeans.scala
> +    env.enableCheckpointing(parameters.ckpInterval, CheckpointingMode.EXACTLY_ONCE)
Please, if you use parameter here, then bring this best practice also on `CheckpointEvaluate`

2017-09-20 15:51 UTC, spi-x-i commented on flink-jpmml-examples/src/main/scala/io/radicalbit/examples/CheckpointEvaluate.scala
> +    env.enableCheckpointing(1000, CheckpointingMode.EXACTLY_ONCE)
specify long please

2017-09-20 15:52 UTC, francescofrontera commented on flink-jpmml-examples/README.md
> +Iris(,sepalLength: Double, sepalWidth: Double, petalLength: Double, petalWidth: Double)
I still haven't finished the Readme!

2017-09-20 16:56 UTC, spi-x-i requested changes

2017-09-20 16:56 UTC, spi-x-i commented on flink-jpmml-examples/README.md
> +_if you like testing a fault-tolerance of the operator you can run a `CheckpointEvaluate` example._
testing the fault-tolerance behaviour of the operator

2017-09-20 16:56 UTC, spi-x-i commented on flink-jpmml-examples/README.md
> +4) Put the model via socket, in this case you can use the models in `flink-jpmml-assets`:
Put --> Send

2017-09-20 16:56 UTC, spi-x-i commented on flink-jpmml-examples/README.md
> +_you can show the job's status in Flink UI on http://localhost:8081_
you can see

2017-09-20 16:56 UTC, spi-x-i commented on flink-jpmml-examples/README.md
> +_At this point, when the job is restarted, there's no need to reload the models in control stream because you should see the models from the last checkpoint_
there's no need to re-send the models info by control stream

2017-09-20 16:56 UTC, spi-x-i commented on flink-jpmml-examples/src/main/scala/io/radicalbit/examples/CheckpointEvaluate.scala
> +    * */
breakline for closing comments

2017-09-20 16:59 UTC, spi-x-i approved these changes

2017-09-21 06:10 UTC, maocorte approved these changes

2017-09-21 07:32 UTC, merged