[#29] Update readme to 0.6.0
radicalbit/flink-jpmml pull request #41
Opened 2017-09-20 15:40 UTC by spi-x-i

You can see preview of this [here](https://github.com/spi-x-i/flink-jpmml/tree/feature/%2329-update-README-to-0.6.0)

2017-09-20 16:55 UTC, riccardo14 requested changes

2017-09-20 16:55 UTC, riccardo14 commented on README.md
> +100 and B depth 5 on width 200, and you desire to have a comparison between them, so likely your can identify
your -> you

2017-09-20 16:55 UTC, riccardo14 commented on README.md
> + formatted as `"<modelApplication>_<modelVersion>"` and a timestamp.
typo `

2017-09-20 20:01 UTC, riccardo14 approved these changes

2017-09-21 06:30 UTC, maocorte reviewed
maybe `architecture.png` could be moved into a dedicated folder (for example `images/`) so it is not included in the builded jar

2017-09-21 06:30 UTC, maocorte commented on README.md
> +    * Snapshot: `"io.radicalbit" %% "flink-jpmml-scala" % "0.7.0-SNAPSHOT"`
Should be also updated the project version into `version.sbt` reflecting the changes

2017-09-21 07:35 UTC, maocorte approved these changes

2017-09-21 07:40 UTC, maocorte approved these changes

2017-09-21 07:43 UTC, merged